.TH BUPM-FETCH 1 "2026-01-19" "bupm 1.x" "Administration Frontend"
.SH NAME
bupm-fetch \- show package informaation

.SH SYNOPSIS
.B bupm fetch
.RI [package]

.SH DESCRIPTION
bupm fetch provides an easy way to see package information. As of bupm 1.1.5, it displays name, version, description, and target files to copy.

.SH COMMANDS
.TP
.B fetch <package>
Fetches the pkgspec.yaml for the package from the repository.

.SH EXAMPLES
.RS
bupm fetch hello_world

.SH SEE-ALSO
bupm(1)

