.TH BUPM-REPO 1 "2026-01-19" "bupm 1.x" "Administrative Commands"
.SH NAME
bupm-repo \- software comes from more places

.SH SYNOPSIS
.B bupm repo
.RI [set, show, update]

.SH DESCRIPTION
.B bupm repo
is the bupm front-end using for managing repositories. It provides access to modifying and reading /etc/bupm/repositories in an easier way, and allows synchronising the repository with the local package database. 

.SH COMMANDS
.TP
.B set <repo>
Set the repository (defined in /etc/bupm/repositories) to the provided text in <repo>.
(Equivalent to editing the config file in most other package managers.)

.TP
.B show
Show the currently active repository.
(Equivalent to running the cat command on the repository file.)

.TP
.B update
Update the /etc/bupm/pkgs and pkgtxt files, which contain information about the available packages in the repository.
(Equivalent to apt update, dnf makecache or pacman -Sy.)

.SH EXAMPLES
.RS
bupm repo set https://raw.githubusercontent.com/OS-Scratch/bupm_source/main
.br
bupm repo update

.SH SEE-ALSO 
bupm-install(1) bupm-fetch(1)

